apiVersion: v1
kind: Service
metadata:
  name: nginx-replica
  labels:
    app: nginx-replica

spec:
  selector:
    app: nginx-replica
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
    