apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  labels: 
    app:  nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: web
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        volumeMounts:
          - mountPath: "/var/test"
            name: myvolume
      volumes:
      - name: myvolume
        persistentVolumeClaim:
          claimName: myclaim-1