apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
    tier: frontend
    
spec:
  containers:
    - name: nginx
      image: nginx
#   - name: redis
#     image: redis