apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim-1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: azurefile-csi-premium
